version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: gf-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gf-api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/gestao_financeira
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gf-web
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - api
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  mongo_data:
